# No warranty.  No guarantees of any sort.
# Creative Commons Attribution-Share Alike 3.0 United States License

require 'rake/clean'

SRC = FileList['*.hs']
CLEAN.include('**/*~')
CLOBBER.include('**/*.hi', '**/*.o', "a.out", "nofrac")
CLOBBER.include("images/*")

YAMLS = FileList['../yaml/*.yml']
PPMS = YAMLS.pathmap("images/%f").ext(".ppm")
GIFS = PPMS.ext(".gif")

task :default => :compile

desc "compiles the nofrac executable with GHC"
task :compile do
  ["nofrac.hs", "Tests.hs"].each do |source|
    sh "ghc -O2 -threaded -rtsopts --make #{source}"
  end
end

task :test => :compile do
  sh "./Tests"
end

desc "compiles the code and generates GIFs"
task :generate => [:default, *GIFS]

GIFS.zip(PPMS).each do |gif, ppm|
  file gif => ppm do
    sh "convert #{ppm} #{gif}"
  end
end

PPMS.zip(YAMLS).each do |ppm, yml|
  file ppm => [yml, "nofrac"] do
    sh "nofrac #{yml} #{ppm}"
  end
end

task :parallel => :compile do
  [1, 2, 4].each do |procs|
    sh "time ./nofrac +RTS -N#{procs} -RTS ../yaml/burningship-zoom-green.yml images/burningship-p#{procs}.ppm"
  end
end
