#!/usr/bin/env escript
% Creative Commons Attribution-Share Alike 3.0 United States License

-export([main/1]).
-import(fractals_driver, [main/0]).
-import(yaml).

main(_) ->
    [_, ConfigFilename, OutputFilename] = init:get_plain_arguments(),
    Config = [{"outputfile", OutputFilename} | yaml:parse_file(ConfigFilename)],
    fractals_driver:main(Config).
