require 'rake/clean'

CLEAN.include('*.beam', "*.gif", "*.ppm")
ERLS  = FileList['*.erl']
BEAMS = ERLS.ext('.beam')

rule '.beam' => '.erl' do |t|
  sh "erlc #{t.source}"
end

task :default => BEAMS

task :generate => "mandelbrot.gif"

rule '.gif' => '.ppm' do |t|
  sh "convert #{t.source} #{t.name}"
end

file "mandelbrot.ppm" => BEAMS do
  sh "nofrac"
end
