require 'rake/clean'

ERLS  = FileList['*.erl']
BEAMS = ERLS.ext('.beam')

YAMLS = FileList['../yaml/*.yml']
PPMS = YAMLS.pathmap("images/%f").ext(".ppm")
GIFS = PPMS.ext(".gif")

rule '.beam' => '.erl' do |t|
  sh "erlc #{t.source}"
end

task :default => :beams

task :generate => GIFS

task :beams => BEAMS

GIFS.zip(PPMS).each do |gif, ppm|
  file gif => ppm do
    sh "convert #{ppm} #{gif}"
  end
end

PPMS.zip(YAMLS).each do |ppm, yml|
  file ppm => [yml, :beams] do
    sh "nofrac #{yml} #{ppm}"
  end
end

CLEAN.include("*.dump")
CLEAN.include(BEAMS, PPMS, GIFS)
