# No warranty.  No guarantees of any sort.
# Creative Commons Attribution-Share Alike 3.0 United States License

require 'rake/clean'

ERLS  = FileList['*.erl']
BEAMS = ERLS.ext('.beam')

YAMLS = FileList['../yaml/*.yml']
PPMS = YAMLS.pathmap("images/%f").ext(".ppm")
GIFS = PPMS.ext(".gif")

rule '.beam' => '.erl' do |t|
  sh "erlc #{t.source}"
end

task :default => :compile

desc "compiles the code and generates GIFs"
task :generate => [:compile, *GIFS]

desc "compiles the code"
task :compile => BEAMS

GIFS.zip(PPMS).each do |gif, ppm|
  file gif => ppm do
    sh "convert #{ppm} #{gif}"
  end
end

PPMS.zip(YAMLS).each do |ppm, yml|
  file ppm => [yml, :compile] do
    sh "nofrac #{yml} #{ppm}"
  end
end

CLEAN.include("*.dump")
CLEAN.include(BEAMS, PPMS, GIFS)
