# No warranty.  No guarantees of any sort.
# Creative Commons Attribution-Share Alike 3.0 United States License

require 'rake/clean'

CLEAN.include('**/*~')
CLOBBER.include("mandelbrot")
CLOBBER.include("images/*")

JSONS = FileList['../json/*.json']
PPMS = JSONS.pathmap("images/%f").ext(".ppm")
GIFS = PPMS.ext(".gif")

task :default => :compile

desc "compiles the mandelbrot executable"
task :compile do
  sh "mix escript.build"
end

task :test do
  sh "mix test"
end

desc "compiles the code and generates GIFs"
task :generate => [:default, *GIFS]

GIFS.zip(PPMS).each do |gif, ppm|
  file gif => ppm do
    sh "convert #{ppm} #{gif}"
  end
end

PPMS.zip(JSONS).each do |ppm, json|
  file ppm => [json, :compile] do
    sh "mandelbrot #{json} #{ppm}"
  end
end

task :parallel => :compile do
  # is this any different for an Elixir program?
end
